### ISSUE TITLE
The method name Input::as_slice_less_safe is confusing

### ISSUE THREAD

**Issue by dlight** [briansmith/untrusted#10]
Because the method itself isn't actually less safe.

My guess is that the name `as_slice_less_safe` conveys that the slice is returned without verifying if the input is valid, which could be seen as a safety hazard if it's later processed by an unsafe function. But any input at all for an unsafe function is a safety hazard, whether it has been sanitized by safe code or not -- when safety is at stake, an unsafe function must not trust the behavior of a safe function defined elsewhere.

So I suggest renaming it. Besides `as_slice`, there are other, more descriptive terms, like:

* `as_raw_slice`

* `as_slice_unchecked`

* `as_slice_unverified`

* `as_slice_unchecked_input`

* `as_slice_unverified_input`

**Comment by briansmith** [comment]
The function is named "less_safe" and not "unsafe" because we're not trying to convey anything about "unsafe" semantics as `unsafe` is defined in Rust.

By "less safe" we mean, in particular, that when you have the input as a slice, we can no longer guarantee that accessing the input won't panic (`Input` and `Reader` can't panic but slice indexing can), we cannot guarantee that you'll always iterate through to the end of the input (like `Input.read_all()` guarantees), etc. 
 Put another way, the goal of the annoying name is to discourage the function from being called, in favor of using the `Input`/`Reader` framework as much as possible.

With that in mind, I don't think any of your suggested names are better than the current name (`as_raw_slice` seems definitely worse; the other ones I'm neutral on). I suggest we live with the annoying name (and yes, it annoys me too) and move on.

**Comment by briansmith** [comment]
Closing this, with the justification already given by the previous comment.
