### ISSUE TITLE
Older versions getting yanked?

### ISSUE THREAD

**Issue by opensourcegeek** [briansmith/untrusted#29]
I'm seeing some older versions of your libs being yanked, I just noticed one of the dependencies I've is on trust-dns and it depends on untrusted version 0.3 and it looks like that's been yanked too. Is there a way to work around without upgrading trust-dns please? I don't want to make code changes if possible. Thanks

**Comment by est31** [comment]
I guess this is due to the same reasons as https://github.com/briansmith/ring/issues/774 .

Maybe @icefoxen can use [isildur](https://crates.io/crates/isildur) or alternatively you can also use my `ignore-yanked` [patch](https://github.com/est31/cargo/commit/1c087ee0026039dea4370adc540543427a506568.patch) for cargo and then do `--ignore-yanked` every time you update.

**Comment by icefoxen** [comment]
There's already a republish of `untrusted`: https://crates.io/crates/detsurtnu .  Use at your own risk.

**Comment by Darkspirit** [comment]
> I just noticed one of the dependencies I've is on trust-dns and it depends on untrusted version 0.3

[trust-dns](https://crates.io/crates/trust-dns) depends on `untrusted ^0.6`. It is not yanked.
That's been the case since [0.15.0](https://crates.io/crates/trust-dns/0.15.0) from November 1, 2018.

[trust-dns 0.10.1](https://crates.io/crates/trust-dns/0.10.1) from **May 9, 2017** was the last version depending on `untrusted ^0.3`.
[trust-dns 0.10.2](https://crates.io/crates/trust-dns/0.10.2) depended on `untrusted ^0.5`.

Please try to adopt security fixes and other improvements. It's only a few minutes of work and shows appreciation to upstream authors doing all this for free. Please don't deploy deprecated software. How would it otherwise possible to set the right incentives towards security? Thank you. ;-)

**Comment by opensourcegeek** [comment]
@Darkspirit I totally understand your spirit in making sure code runs the latest and greatest all the time. However it's hard to convince people to get CRs raised. As much as I don't want to run outdated code it's hard to upgrade at the moment due to practical reasons, hopefully you'd appreciate. There's some time scheduled to upgrade deps, may be it would happen sooner rather than later.

Just out of curiosity is there a reason for yanking libs? Was there a security issue with the libs or something?

**Comment by Darkspirit** [comment]
Using network or security libraries is a constant process of upgrading to a maintained or latest stable version. Of course it is super frustrating to be suddenly confronted with an urgent but long overdue task. :/
Please see briansmith/ring#774 for some background and other solutions.

**Comment by briansmith** [comment]
@opensourcegeek If you or anybody else has questions about versions other than the latest published version, please email them to me at brian@briansmith.org. I only support the latest version published to crates.io on GitHub.
