### ISSUE TITLE
Tag 0.7.0 and 0.7.1 release in git?

### ISSUE THREAD

**Issue by alex** [briansmith/untrusted#36]
It'd be great if releases could be tagged in git, that way tools can more easily generate diffs/changeloges between them. Thanks!

**Comment by briansmith** [comment]
I stopped doing the tags because there's no guarantee that what GitHub claims to be version X is actually what is in the version X on crates.io. Therefore, it's potentially very misleading if they get out of sync. The published crate itself should contain the commit hash of the commit it was built from.
